version: 2.1

orbs:
  python: circleci/python@1.3.2

jobs:
  test_python:
    parameters:
      docker_image:
        type: string
      tox_cmd:
        type: string
    docker:
      - image: << parameters.docker_image >>
    steps:
      - checkout
      - run: python setup.py bdist_wheel
      - run: pip install -e .
      - run: pip install tox
      - run: << parameters.tox_cmd >>

  pypi_distribution:
    docker:
      - image: cimg/python:3.9.2
    steps:
      - checkout
      - run:
          command: |
            python setup.py bdist_wheel sdist
            pip install --upgrade pip
            pip install twine==3.3.0
            twine upload --repository-url https://upload.pypi.org/legacy/ -u __token__ -p ${PYPI_PYTHON_KEYCLOAK_API_CLIENT_TOKEN} dist/*

workflows:
  version: 2
  app:
    jobs:
      - test_python:
          name: test_python_39
          docker_image: "cimg/python:3.9.2"
          tox_cmd: tox -e py39
      - test_python:
          name: test_python_310
          docker_image: "cimg/python:3.10.13"
          tox_cmd: tox -e py310
      - test_python:
          name: test_python_311
          docker_image: "cimg/python:3.11.4"
          tox_cmd: tox -e py311
      - test_python:
          name: test_python_312
          docker_image: "cimg/python:3.12.6"
          tox_cmd: tox -e py312
      - approve_pypi_distribution:
          type: approval
          requires:
            - test_python_39
            - test_python_310
            - test_python_311
            - test_python_312
          filters:
            branches:
              only:
                - main
      - pypi_distribution:
          requires:
            - approve_pypi_distribution
          filters:
            branches:
              only:
                - main
