version: 2.1

orbs:
  python: circleci/python@1.3.2

jobs:
  test_py36:
    docker:
      - image: cimg/python:3.6.13
    steps:
      - checkout
      - run: python setup.py bdist_wheel
      - run: pip install -e .
      - run: pip install tox
      - run: tox -e py36
  test_py37:
    docker:
      - image: cimg/python:3.7.10
    steps:
      - checkout
      - run: python setup.py bdist_wheel
      - run: pip install -e .
      - run: pip install tox
      - run: tox -e py37
  test_py38:
    docker:
        - image: cimg/python:3.8.8
    steps:
      - checkout
      - run: python setup.py bdist_wheel
      - run: pip install -e .
      - run: pip install tox
      - run: tox -e py38
  test_py39:
    docker:
        - image: cimg/python:3.9.2
    steps:
      - checkout
      - run: python setup.py bdist_wheel
      - run: pip install -e .
      - run: pip install tox
      - run: tox -e py39
  pypi_distribution:
    docker:
      - image: cimg/python:3.9.2
    steps:
      - checkout
      - run:
          command: |
              python setup.py bdist_wheel sdist
              pip install --upgrade pip
              pip install twine==3.3.0
              twine upload --repository-url https://upload.pypi.org/legacy/ -u __token__ -p ${PYPI_PYTHON_KEYCLOAK_API_CLIENT_TOKEN} dist/*

workflows:
  version: 2
  app:
    jobs:
      - test_py36
      - test_py37
      - test_py38
      - test_py39
      - approve_pypi_distribution:
          type: approval
          requires:
            - test_py36
            - test_py37
            - test_py38
            - test_py39
          filters:
            branches:
              only:
                - main
      - pypi_distribution:
          requires:
            - approve_pypi_distribution
          filters:
            branches:
              only:
                - main
